"""Deterministic Soroban contract scaffold generator.

Builds the in-memory file rows for a minimal, correct Soroban contract project
(a ``Cargo.toml`` with ``soroban-sdk``, a ``src/lib.rs`` with a
``#[contract]`` / ``#[contractimpl]`` contract, a ``.soroban`` testnet config,
a ``README``, and a ``.gitignore``).

Rules:

* **Generation only.** No ``cargo`` is executed and no network operation is
  performed. The scaffold is explicitly documented as *not compiled/verified* in
  this environment — nothing here claims the code builds.
* **No secrets.** No keys, no ``~/.soroban`` config, no deploy accounts.
* **Deterministic & bounded.** Given a name, the same small set of plain-text
  files is produced every time; the returned rows match the shape consumed by
  ``app.services.importing.store_project_files`` so a scaffold can be imported
  into a workspace like any other project.
"""

from __future__ import annotations

import re

from app.services.importing import detect_language

#: Crate/package name used when none is supplied.
DEFAULT_CRATE_NAME = "hello_world"

#: Cargo package names allow ``[a-zA-Z0-9_-]``; keep scaffolds conservative.
_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
_MAX_NAME_CHARS = 40


class ScaffoldError(ValueError):
    """Raised when a scaffold name is invalid for a Cargo package."""


def normalize_crate_name(label: str | None) -> str:
    """Return a safe Cargo crate/package name derived from ``label``.

    Empty input becomes :data:`DEFAULT_CRATE_NAME`. Otherwise the text is
    lowercased, non-``[a-z0-9]`` runs become ``_``, leading/trailing separators
    are trimmed, and a digit cannot start the name (Cargo requires an
    alphabetic/``_`` start). Over-long input raises :class:`ScaffoldError`.
    """
    if label is None or not str(label).strip():
        return DEFAULT_CRATE_NAME
    text = str(label).strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text).strip("_")
    if not text:
        return DEFAULT_CRATE_NAME
    if len(text) > _MAX_NAME_CHARS:
        raise ScaffoldError("Scaffold name is too long (max 40 characters).")
    if text[0].isdigit():
        text = "c_" + text
    if not _NAME_RE.match(text):
        raise ScaffoldError("Scaffold name contains unsupported characters.")
    return text


def _pascal(crate_name: str) -> str:
    """Derive a Rust type name (``hello_world`` -> ``HelloWorld``)."""
    return "".join(part[:1].upper() + part[1:] for part in crate_name.split("_"))


def _file_row(path: str, text: str) -> dict:
    """Build a sanitized file row from plain text (never binary)."""
    raw = text.encode("utf-8")
    return {
        "path": path,
        "size": len(raw),
        "is_binary": False,
        "language": detect_language(path),
        "content": text,
    }


def _cargo_toml(crate_name: str) -> str:
    return f"""[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "21.0.0"

[dev-dependencies]
soroban-sdk = {{ version = "21.0.0", features = ["testutils"] }}

[profile.release]
opt-level = 3
"""


def _lib_rs(crate_name: str) -> str:
    contract_type = _pascal(crate_name)
    return f"""#![no_std]
use soroban_sdk::{{contract, contractimpl, symbol_short, Env, Symbol}};

/// A minimal generated Soroban contract.
///
/// Review this contract before building or deploying it. It is a starting
/// point, not a finished, audited implementation.
#[contract]
pub struct {contract_type};

#[contractimpl]
impl {contract_type} {{
    /// Greet ``to``: record who was greeted and return a fixed acknowledgement.
    pub fn hello(env: Env, to: Symbol) -> Symbol {{
        env.storage().instance().set(&symbol_short!("to"), &to);
        symbol_short!("Hello")
    }}
}}
"""


def _soroban_config() -> str:
    return """# Generated scaffold — Soroban CLI testnet network configuration.
# This file only describes the network for the Soroban CLI; it is never used at
# contract runtime. Add your own keys/endpoints before any deployment and never
# commit secrets.
[network.testnet]
rpc_url = "https://soroban-testnet.stellar.org"
network_passphrase = "Test SDF Network ; September 2015"
"""


def _readme(crate_name: str) -> str:
    return f"""# {crate_name}

A minimal, generated **Soroban** smart-contract project scaffold:

- `Cargo.toml` — crate manifest with the `soroban-sdk` dependency.
- `src/lib.rs` — a `#[contract]` / `#[contractimpl]` hello contract.
- `.soroban/config.toml` — testnet network configuration for the Soroban CLI.

## Notes

- This project was generated by AI Code Assistant. It has **not** been compiled
  or verified with `cargo build` in this environment.
- Building and deploying is your responsibility: review `src/lib.rs`, then use
  the Soroban toolchain (`cargo build --target wasm32-unknown-unknown --release`
  followed by `stellar contract deploy ...`) against your chosen network.
- Keep keys out of the repository. Never commit secrets.
"""


def _gitignore() -> str:
    return "/target\nCargo.lock\n"


def soroban_scaffold_rows(name: str | None = None) -> list[dict]:
    """Return the scaffold file rows (import-ready) for an optional ``name``.

    ``name`` is normalized into a valid Cargo package name (see
    :func:`normalize_crate_name`); an empty/invalid-but-normalizable value falls
    back to :data:`DEFAULT_CRATE_NAME`, and an over-long value raises
    :class:`ScaffoldError`.
    """
    crate_name = normalize_crate_name(name)
    files = [
        ("Cargo.toml", _cargo_toml(crate_name)),
        ("src/lib.rs", _lib_rs(crate_name)),
        (".soroban/config.toml", _soroban_config()),
        ("README.md", _readme(crate_name)),
        (".gitignore", _gitignore()),
    ]
    return [_file_row(path, text) for path, text in files]
