"""add plugin system tables for phase 8

Revision ID: b3c2d1a0f9e8
Revises: a38bfbf71b9e
Create Date: 2026-08-27 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c2d1a0f9e8'
down_revision = 'a38bfbf71b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('entry_point', sa.String(length=500), nullable=False),
    sa.Column('manifest_path', sa.String(length=2000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', name='uq_plugins_plugin_id')
    )
    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugins_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugins_plugin_id'), ['plugin_id'], unique=True)

    op.create_table('plugin_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'workspace_id', name='uq_plugin_installations_plugin_workspace')
    )
    with op.batch_alter_table('plugin_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_installations_plugin_id'), ['plugin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_installations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('capability_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_installation_id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=50), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plugin_installation_id'], ['plugin_installations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_installation_id', 'capability', name='uq_capability_grants_plugin_capability')
    )
    with op.batch_alter_table('capability_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capability_grants_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_capability_grants_plugin_installation_id'), ['plugin_installation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capability_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capability_grants_plugin_installation_id'))
        batch_op.drop_index(batch_op.f('ix_capability_grants_capability'))

    op.drop_table('capability_grants')

    with op.batch_alter_table('plugin_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_installations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_installations_plugin_id'))

    op.drop_table('plugin_installations')

    with op.batch_alter_table('plugins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugins_plugin_id'))
        batch_op.drop_index(batch_op.f('ix_plugins_enabled'))

    op.drop_table('plugins')
    # ### end Alembic commands ###
