"""add plugin system tables for phase 8

Revision ID: b3c2d1a0f9e8
Revises: a38bfbf71b9e
Create Date: 2026-08-27 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c2d1a0f9e8'
down_revision = 'a38bfbf71b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('entry_point', sa.String(length=512), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('plugin_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('granted_capabilities', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('installed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'workspace_id', name='uq_plugin_installation')
    )
    with op.batch_alter_table('plugin_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_installations_plugin_id'), ['plugin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_installations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('plugin_capability_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'workspace_id', 'capability', name='uq_plugin_capability_grant')
    )
    with op.batch_alter_table('plugin_capability_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin_capability_grants_plugin_id'), ['plugin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plugin_capability_grants_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin_capability_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_capability_grants_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_capability_grants_plugin_id'))

    op.drop_table('plugin_capability_grants')

    with op.batch_alter_table('plugin_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin_installations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_plugin_installations_plugin_id'))

    op.drop_table('plugin_installations')

    op.drop_table('plugins')
    # ### end Alembic commands ###
